export type NFLPlayer = {
  active: boolean
  age?: number
  birth_city?: string
  birth_country?: string
  birth_date?: string
  birth_state?: string
  college?: string
  depth_chart_order?: number
  depth_chart_position?: string
  espn_id?: number
  fantasy_data_id?: number
  fantasy_positions?: Array<string>
  first_name: string
  full_name: string
  gsis_id?: string
  hashtag?: string
  height?: string
  high_school?: string
  injury_body_part?: string
  injury_notes?: string
  injury_start_date?: string
  injury_status?: string
  last_name?: string
  metadata?: string
  news_updated?: number
  number?: number
  pandascore_id?: string
  player_id?: string
  position?: string
  practice_description?: string
  practice_participation?: string
  rotowire_id?: number
  rotoworld_id?: number
  search_first_name?: string
  search_full_name?: string
  search_last_name?: string
  search_rank?: number
  sport?: string
  sportradar_id?: string
  stats_id?: number
  status?: string
  swish_id?: number
  team?: string
  weight?: string
  yahoo_id?: number
  years_exp?: number
}